using Grasshopper;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Data;
using Grasshopper.Kernel.Types;
using Rhino;
using Rhino.Geometry;
using System;
using System.Collections.Generic;
using System.Linq;
using static Mimikyu.Helper.ScannerHelper;

namespace Mimikyu
{
    public class GH_DefectPose : GH_Component
    {
        /// <summary>
        /// Initializes a new instance of the GH_DefectPose class.
        /// </summary>
        public GH_DefectPose()
          : base("DefectPose", "DP",
              "Generate detailed scan poses from 3D defect point branches using local 3D OBB",
              "Mimikyu", "PC_Robot")
        {
        }

        /// <summary>
        /// Registers all the input parameters for this component.
        /// </summary>
        protected override void RegisterInputParams(
            GH_Component.GH_InputParamManager pManager)
        {
            pManager.AddGenericParameter("Scan Object","SO","ScanObject generated by GH_ObjectPose",GH_ParamAccess.list);
            pManager.AddPointParameter("Defect Points","Dpts","Tree of 3D defect points with path {poseIndex; sideId; defectId}",GH_ParamAccess.tree);
            pManager.AddNumberParameter("Capture Width", "W","Camera/scanner capture width in mm",GH_ParamAccess.item,428.0);
            pManager.AddNumberParameter("Capture Height","H", "Camera/scanner capture height in mm",GH_ParamAccess.item,330.0);
            pManager.AddNumberParameter("Distance", "D","Camera distance from scan target in mm", GH_ParamAccess.item,500.0);
            pManager.AddNumberParameter("Overlap","O","Overlap ratio between neighbouring captures, e.g. 0.10 = 10%", GH_ParamAccess.item,0.10);
            pManager.AddNumberParameter("Merge Distance", "Md", "Distance in mm used to merge nearby defect branches into one scan region", GH_ParamAccess.item, 330.0);
            pManager.AddIntegerParameter("Max Hull Points","Mh","Maximum number of points used to compute the convex hull per merged region.", GH_ParamAccess.item,120);
            pManager.AddNumberParameter("3D Threshold","T3D","If the smallest OBB dimension is larger than this value, the region is marked as 3D/non-planar.", GH_ParamAccess.item,20.0);
            pManager.AddNumberParameter("Tilt Angle", "A", "Additional scan angle on each side of the surface-normal scan, in degrees.", GH_ParamAccess.item, 10.0);

            pManager[2].Optional = true;
            pManager[3].Optional = true;
            pManager[4].Optional = true;
            pManager[5].Optional = true;
            pManager[6].Optional = true;
            pManager[7].Optional = true;
            pManager[8].Optional = true;
            pManager[9].Optional = true;
        }

        /// <summary>
        /// Registers all the output parameters for this component.
        /// </summary>
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
        {

            pManager.AddPlaneParameter("Scan Poses", "P", "Generated camera scan poses. One branch per merged scan region.", GH_ParamAccess.tree);
            pManager.AddBoxParameter("Region OBBs", "B", "Minimum 3D OBB for each merged defect scan region.", GH_ParamAccess.tree);
            pManager.AddPointParameter("Region Points", "Rpts", "Merged defect points. One branch per final scan region.", GH_ParamAccess.tree);
            pManager.AddMeshParameter("Hull Meshes", "H", "Convex hull mesh used for each merged scan region.", GH_ParamAccess.tree);
            pManager.AddTextParameter("Info", "I", "Debug information per merged scan region.", GH_ParamAccess.tree);

        }

        /// <summary>
        /// This is the method that actually does the work.
        /// </summary>
        /// <param name="DA">The DA object is used to retrieve from inputs and store in outputs.</param>
        protected override void SolveInstance(IGH_DataAccess DA)
        {

            List<ScanObject> scanObjects = new List<ScanObject>();
            GH_Structure<GH_Point> defectTree = null;

            double captureW = 428.0;
            double captureH = 330.0;
            double distance = 500.0;
            double overlap = 0.10;
            double mergeDistance = 330.0;
            int maxHullPoints = 120;
            double threeDThreshold = 5.0;
            double tiltAngleDegrees = 10.0;


            if (!DA.GetDataList(0, scanObjects)) return;

            foreach (ScanObject scanObject in scanObjects)
            { 
                if (scanObject == null ||
                    scanObject.Mesh == null ||
                    !scanObject.Mesh.IsValid)
                {
                    AddRuntimeMessage(
                        GH_RuntimeMessageLevel.Error,
                        "Input SO is not a valid ScanObject from GH_ObjectPose.");

                    return;
                }
            }

            if (!DA.GetDataTree(1, out defectTree))
                return;

            DA.GetData(2, ref captureW);
            DA.GetData(3, ref captureH);
            DA.GetData(4, ref distance);
            DA.GetData(5, ref overlap);
            DA.GetData(6, ref mergeDistance);
            DA.GetData(7, ref maxHullPoints);
            DA.GetData(8, ref threeDThreshold);
            DA.GetData(9, ref tiltAngleDegrees);

            if (defectTree == null || defectTree.PathCount == 0)
            {
                AddRuntimeMessage(
                    GH_RuntimeMessageLevel.Warning,
                    "No defect point branches found.");

                return;
            }
            List<RawDefectBranch> rawBranches = ReadRawDefectBranches(defectTree);
            if (rawBranches.Count == 0)
            {
                AddRuntimeMessage(
                    GH_RuntimeMessageLevel.Warning,
                    "No valid defect points found.");

                return;
            }

            DataTree<Plane> poseTree = new DataTree<Plane>();
            DataTree<Box> boxTree = new DataTree<Box>();
            DataTree<Point3d> regionPointTree = new DataTree<Point3d>();
            DataTree<Mesh> hullTree = new DataTree<Mesh>();
            DataTree<string> infoTree = new DataTree<string>();

            int piece = 0;
            foreach (ScanObject scanObject in scanObjects)
            { 
                Mesh objectMesh =
                    scanObject.Mesh;


                if (objectMesh == null || !objectMesh.IsValid)
                {
                    AddRuntimeMessage(
                        GH_RuntimeMessageLevel.Error,
                        "Object mesh is null or invalid.");

                    return;
                }


                objectMesh.FaceNormals.ComputeFaceNormals();
                objectMesh.Normals.ComputeNormals();
                captureW = Math.Abs(captureW);
                captureH = Math.Abs(captureH);
                distance = Math.Abs(distance);
                mergeDistance = Math.Abs(mergeDistance);

                maxHullPoints = Math.Max(20, maxHullPoints);

                overlap = Math.Max(0.0, Math.Min(0.9, overlap));
                tiltAngleDegrees = Math.Max( 0.0, Math.Min(45.0, Math.Abs(tiltAngleDegrees)));

                double stepU = captureW * (1.0 - overlap);
                double stepV = captureH * (1.0 - overlap);

                if (stepU <= RhinoMath.ZeroTolerance)
                    stepU = captureW;

                if (stepV <= RhinoMath.ZeroTolerance)
                    stepV = captureH;

                // ------------------------------------------------------------
                // 1. Read raw defect branches
                // ------------------------------------------------------------
                var pieceBranches = rawBranches.Where(b => b.PieceId == piece).ToList();

                // ------------------------------------------------------------
                // 2. Merge nearby raw branches into final scan regions
                // ------------------------------------------------------------
                List<MergedRegion> regions =
                    MergeNearbyBranches(
                        pieceBranches,
                        mergeDistance);

                if (regions.Count == 0)
                {
                    AddRuntimeMessage(
                        GH_RuntimeMessageLevel.Warning,
                        "No merged defect regions created.");

                    return;
                }

                // ------------------------------------------------------------
                // 3. For each merged region, create hull, compute OBB, tile poses
                // ------------------------------------------------------------
                for (int r = 0; r < regions.Count; r++)
                {
                    MergedRegion region = regions[r];
                    GH_Path outPath = new GH_Path(piece, r);

                    List<Point3d> regionPts = region.Points;

                    if (regionPts == null || regionPts.Count < 4)
                    {
                        infoTree.Add(
                            "Skipped region " + r +
                            ": fewer than 4 points after merging.",
                            outPath);

                        continue;
                    }

                    foreach (Point3d p in regionPts)
                        regionPointTree.Add(p, outPath);

                    List<Point3d> hullInputPts =
                        RemoveDuplicatePoints(
                            regionPts,
                            RhinoDoc.ActiveDoc.ModelAbsoluteTolerance);


                    // ------------------------------------------------------------
                    // Decide if this merged region is planar or truly 3D
                    // ------------------------------------------------------------
                    bool isPlanar;
                    double planarThickness;

                    isPlanar =
                        IsPointSetPlanar(
                            hullInputPts,
                            threeDThreshold,
                            out planarThickness);

                    Box regionBox = Box.Unset;
                    Mesh hullMesh = null;

                    if (isPlanar)
                    {
                        // --------------------------------------------------------
                        // Planar defect:
                        // Use best-fit plane + planar local bounding box.
                        // This is better for cracks, knots, stains, surface damage.
                        // --------------------------------------------------------
                        bool okPlanarBox =
                            TryCreatePlanarDefectBox(
                                hullInputPts,
                                out regionBox);

                        if (!okPlanarBox || !regionBox.IsValid)
                        {
                            infoTree.Add(
                                "Skipped region " + r +
                                ": failed to create planar defect box.",
                                outPath);

                            continue;
                        }

                        infoTree.Add(
                            "Region " + r +
                            " uses PLANAR workflow. Thickness = " +
                            planarThickness.ToString("F2"),
                            outPath);
                    }
                    else
                    {
                        // --------------------------------------------------------
                        // True 3D defect:
                        // Use MIConvexHull + your original minimum 3D OBB.
                        // This is better for broken edges, corner damage, chunks.
                        // --------------------------------------------------------
                        string hullDebug;

                        bool okHull =
                            CreateHullMeshMIConvexHull(
                                hullInputPts,
                                out hullMesh,
                                out hullDebug);

                        infoTree.Add(
                            "Region " + r + " hull debug: " + hullDebug,
                            outPath);

                        if (!okHull || hullMesh == null || !hullMesh.IsValid || hullMesh.Faces.Count == 0)
                        {
                            infoTree.Add(
                                "Skipped region " + r +
                                ": failed to create a valid 3D convex hull.",
                                outPath);

                            continue;
                        }

                        hullMesh.Normals.ComputeNormals();
                        hullMesh.FaceNormals.ComputeFaceNormals();
                        hullMesh.Compact();

                        hullTree.Add(hullMesh, outPath);

                        regionBox =
                            GetMinimumBoundingBox3D(hullMesh);

                        if (!regionBox.IsValid)
                        {
                            infoTree.Add(
                                "Skipped region " + r +
                                ": invalid minimum 3D OBB.",
                                outPath);

                            continue;
                        }

                        infoTree.Add(
                            "Region " + r +
                            " uses 3D HULL workflow. Thickness = " +
                            planarThickness.ToString("F2") +
                            ", hull faces = " + hullMesh.Faces.Count,
                            outPath);
                    }

                    boxTree.Add(regionBox, outPath);

                    Vector3d[] axes;
                    double[] sizes;

                    GetBoxAxesAndSizes(
                        regionBox,
                        out axes,
                        out sizes);

                    int uId;
                    int vId;
                    int nId;

                    GetScanAxisIds(
                        sizes,
                        out uId,
                        out vId,
                        out nId);

                    Vector3d uAxis = axes[uId];
                    Vector3d vAxis = axes[vId];
                    Vector3d boxNormal = axes[nId];

                    uAxis.Unitize();
                    vAxis.Unitize();
                    boxNormal.Unitize();

                    List<Vector3d> scanDirections =
                        GetScanDirections(
                            region,
                            scanObject);

                    RegionType regionType =
                        GetRegionType(region);

                    int primarySideId =
                        region.SideIds.Count > 0
                        ? region.SideIds.First()
                        : (int)Sides.posZ;

                    Vector3d preferredXAxis =
                        scanObject.GetSideUAxis(
                            primarySideId);

                    if (!preferredXAxis.Unitize())
                        preferredXAxis = uAxis;

                    infoTree.Add(
                        "Region " + r +
                        " scan type: " + regionType.ToString() +
                        " | SideIds: " + string.Join(",", region.SideIds) +
                        " | Scan directions: " + scanDirections.Count,
                        outPath);

                    double sizeU = sizes[uId];
                    double sizeV = sizes[vId];
                    double sizeN = sizes[nId];


                    int countU =
                        Math.Max(
                            1,
                            (int)Math.Ceiling(sizeU / stepU));

                    int countV =
                        Math.Max(
                            1,
                            (int)Math.Ceiling(sizeV / stepV));

                    string typeText =
                        sizeN > threeDThreshold
                        ? "3D / non-planar candidate"
                        : "near-surface candidate";

                    infoTree.Add(
                        "Region " + r +
                        " | Raw branches merged: " + string.Join(",", region.RawBranchIndices) +
                        " | Points: " + regionPts.Count +
                        " | Hull points used: " + hullInputPts.Count +
                        " | Size U: " + sizeU.ToString("F2") +
                        " | Size V: " + sizeV.ToString("F2") +
                        " | Thickness: " + sizeN.ToString("F2") +
                        " | countU: " + countU +
                        " | countV: " + countV +
                        " | Type: " + typeText,
                        outPath);

                    // --------------------------------------------------------
                    // 4. Generate tiled scan targets on the OBB middle plane
                    // --------------------------------------------------------
                    for (int row = 0; row < countV; row++)
                    {
                        bool reverse = row % 2 == 1;

                        for (int colIter = 0; colIter < countU; colIter++)
                        {
                            int col =
                                reverse
                                ? countU - 1 - colIter
                                : colIter;

                            double overscan = 0.15; // 15%

                            double marginU =
                                Math.Min(
                                    0.49,
                                    (captureW * (0.5 - overscan)) / sizeU);

                            double marginV =
                                Math.Min(
                                    0.49,
                                    (captureH * (0.5 - overscan)) / sizeV);

                            double tu =
                                countU == 1
                                ? 0.5
                                : marginU +
                                  ((double)col / (countU - 1)) *
                                  (1.0 - 2.0 * marginU);

                            double tv =
                                countV == 1
                                ? 0.5
                                : marginV +
                                  ((double)row / (countV - 1)) *
                                  (1.0 - 2.0 * marginV);

                            double[] t = new double[3];

                            t[uId] = tu;
                            t[vId] = tv;
                            t[nId] = 0.5;

                            Point3d roughTarget =
                                regionBox.PointAt(
                                    t[0],
                                    t[1],
                                    t[2]);

                            Point3d surfaceTarget;
                            Vector3d surfaceNormal;

                            Vector3d preferredSnapNormal =
                                scanDirections.Count > 0
                                ? scanDirections[0]
                                : boxNormal;

                            if (!preferredSnapNormal.Unitize())
                                preferredSnapNormal = boxNormal;

                            bool okSurface =
                                ProjectPointToMeshSurface(
                                    objectMesh,
                                    roughTarget,
                                    preferredSnapNormal,
                                    out surfaceTarget,
                                    out surfaceNormal);

                            if (!okSurface)
                            {
                                infoTree.Add(
                                    "Skipped one target in region " + r +
                                    ": could not snap target to object mesh.",
                                    outPath);

                                continue;
                            }

                            // --------------------------------------------------------
                            // Construct three views from the actual local mesh normal:
                            // 1. Perpendicular to surface
                            // 2. Tilted -A degrees
                            // 3. Tilted +A degrees
                            // --------------------------------------------------------

                            if (!surfaceNormal.Unitize())
                            {
                                infoTree.Add(
                                    "Skipped one target in region " + r +
                                    ": invalid surface normal.",
                                    outPath);

                                continue;
                            }

                            // Mesh normals can point inward or outward depending on the
                            // mesh orientation. Align the local surface normal with the
                            // expected outward scan direction for this object side.
                            Vector3d expectedOutwardDirection =
                                preferredSnapNormal;

                            if (!expectedOutwardDirection.Unitize())
                                expectedOutwardDirection = boxNormal;

                            if (expectedOutwardDirection.Unitize())
                            {
                                if (surfaceNormal * expectedOutwardDirection < 0.0)
                                    surfaceNormal.Reverse();
                            }

                            // Create a stable local horizontal axis projected onto the
                            // tangent plane at the current surface target.
                            Vector3d localXAxis =
                                ProjectVectorToPlane(
                                    preferredXAxis,
                                    surfaceNormal);

                            if (!localXAxis.Unitize())
                            {
                                localXAxis =
                                    ProjectVectorToPlane(
                                        uAxis,
                                        surfaceNormal);
                            }

                            // Final fallback if preferredXAxis and uAxis are both nearly
                            // parallel to the surface normal.
                            if (!localXAxis.Unitize())
                            {
                                localXAxis =
                                    CreatePerpendicularVector(
                                        surfaceNormal);
                            }

                            if (!localXAxis.Unitize())
                            {
                                infoTree.Add(
                                    "Skipped one target in region " + r +
                                    ": could not construct local scan X axis.",
                                    outPath);

                                continue;
                            }

                            // The vertical tangent direction is used as the rotation axis.
                            // Rotating around this axis produces left/right side views.
                            Vector3d tiltAxis =
                                Vector3d.CrossProduct(
                                    surfaceNormal,
                                    localXAxis);

                            if (!tiltAxis.Unitize())
                            {
                                infoTree.Add(
                                    "Skipped one target in region " + r +
                                    ": could not construct tilt axis.",
                                    outPath);

                                continue;
                            }

                            List<Vector3d> finalViewDirections =
                                CreateSurfaceNormalViews(
                                    surfaceNormal,
                                    tiltAxis,
                                    tiltAngleDegrees);

                            // Add three camera poses for this target:
                            // perpendicular, -tilt and +tilt.
                            foreach (Vector3d viewDirRaw in finalViewDirections)
                            {
                                Vector3d viewDir =
                                    viewDirRaw;

                                if (!viewDir.Unitize())
                                    continue;

                                Plane pose =
                                    CreateCameraPlane(
                                        surfaceTarget,
                                        viewDir,
                                        distance,
                                        localXAxis);

                                if (!pose.IsValid)
                                {
                                    infoTree.Add(
                                        "Skipped one pose in region " + r +
                                        ": CreateCameraPlane returned an invalid plane.",
                                        outPath);

                                    continue;
                                }

                                poseTree.Add(
                                    pose,
                                    outPath);
                            }

                        }
                    }
                }
                piece++;
            }

            DA.SetDataTree(0, poseTree);
            DA.SetDataTree(1, boxTree);
            DA.SetDataTree(2, regionPointTree);
            DA.SetDataTree(3, hullTree);
            DA.SetDataTree(4, infoTree);
        }
        /// <summary>
        /// Projects a vector onto a plane defined by its normal.
        /// </summary>
        private static Vector3d ProjectVectorToPlane(
            Vector3d vector,
            Vector3d planeNormal)
        {
            Vector3d normal =
                planeNormal;

            if (!normal.Unitize())
                return Vector3d.Unset;

            return vector -
                   (vector * normal) * normal;
        }


        /// <summary>
        /// Creates an arbitrary vector perpendicular to the supplied normal.
        /// Used only as a fallback when an object-side axis cannot be projected
        /// reliably onto the surface tangent plane.
        /// </summary>
        private static Vector3d CreatePerpendicularVector(
            Vector3d normal)
        {
            Vector3d n =
                normal;

            if (!n.Unitize())
                return Vector3d.Unset;

            Vector3d reference;

            // Choose the global axis least parallel to the surface normal.
            double dotX =
                Math.Abs(n * Vector3d.XAxis);

            double dotY =
                Math.Abs(n * Vector3d.YAxis);

            double dotZ =
                Math.Abs(n * Vector3d.ZAxis);

            if (dotX <= dotY && dotX <= dotZ)
                reference = Vector3d.XAxis;
            else if (dotY <= dotX && dotY <= dotZ)
                reference = Vector3d.YAxis;
            else
                reference = Vector3d.ZAxis;

            Vector3d perpendicular =
                Vector3d.CrossProduct(
                    reference,
                    n);

            if (!perpendicular.Unitize())
                return Vector3d.Unset;

            return perpendicular;
        }


        /// <summary>
        /// Creates three scan directions around a local surface normal:
        /// perpendicular, negative tilt, and positive tilt.
        /// </summary>
        private static List<Vector3d> CreateSurfaceNormalViews(
            Vector3d surfaceNormal,
            Vector3d rotationAxis,
            double tiltDegrees)
        {
            List<Vector3d> directions =
                new List<Vector3d>();

            Vector3d normal =
                surfaceNormal;

            Vector3d axis =
                rotationAxis;

            if (!normal.Unitize())
                return directions;

            if (!axis.Unitize())
            {
                directions.Add(normal);
                return directions;
            }

            double tiltRadians =
                RhinoMath.ToRadians(
                    Math.Abs(tiltDegrees));

            // First pose is exactly perpendicular to the surface.
            directions.Add(normal);

            if (tiltRadians <= RhinoMath.ZeroTolerance)
                return directions;

            // Negative side view.
            Vector3d negativeTilt =
                normal;

            negativeTilt.Transform(
                Transform.Rotation(
                    -tiltRadians,
                    axis,
                    Point3d.Origin));

            if (negativeTilt.Unitize())
                directions.Add(negativeTilt);

            // Positive side view.
            Vector3d positiveTilt =
                normal;

            positiveTilt.Transform(
                Transform.Rotation(
                    tiltRadians,
                    axis,
                    Point3d.Origin));

            if (positiveTilt.Unitize())
                directions.Add(positiveTilt);

            return directions;
        }
        /// <summary>
        /// Provides an Icon for the component.
        /// </summary>
        protected override System.Drawing.Bitmap Icon
        {
            get
            {
                //You can add image files to your project resources and access them like this:
                // return Resources.IconForThisComponent;
                return null;
            }
        }

        /// <summary>
        /// Gets the unique ID for this component. Do not change this ID after release.
        /// </summary>
        public override Guid ComponentGuid
        {
            get { return new Guid("3E83515E-313C-453B-878E-92F39A8BA785"); }
        }
    }
}